apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-overrides
  namespace: observability
data:
  overrides.yaml: |
    overrides:
      "tenant-1":
        metrics_generator:
          processors: [service-graphs, span-metrics]
          disable_collection: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        fsGroup: 10001 
      containers:
        - name: tempo
          image: grafana/tempo:2.5.0
          args: ["-config.file=/etc/tempo/tempo.yaml"]
          ports:
            - name: http
              containerPort: 3200
            - name: grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: overrides
              mountPath: /etc/tempo/overrides
              readOnly: true
            - name: data
              mountPath: /var/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
            items:
              - key: tempo.yaml
                path: tempo.yaml
        - name: overrides
          configMap:
            name: tempo-overrides
            items:
              - key: overrides.yaml
                path: overrides.yaml
        - name: data
          persistentVolumeClaim:
            claimName: tempo-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observability
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
